---
jobs:
- name: test-unit
  public: true
  plan:
    - get: weekly
      trigger: true
    - get: resolvconf-manager-src
    - task: test-unit
      privileged: true
      file: resolvconf-manager-src/ci/tasks/test-unit.yml

resources:
- name: weekly
  type: time
  source:
    start: 3:00 -0700
    stop: 4:30 -0700
    days: [Saturday]

- name: resolvconf-manager-src
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/resolvconf-manager
    branch: master
    private_key: {{github_deployment_private_key}}
    ignore_paths:
    - ci/docker
