---
jobs:
- name: test-unit
  public: true
  plan:
    - get: weekly
      trigger: true
    - get: resolvconf-manager-src
      trigger: true
    - task: test-unit
      privileged: true
      file: resolvconf-manager-src/ci/tasks/test-unit.yml

- name: promote
  public: true
  plan:
    - get: resolvconf-manager-src
      passed:
      - test-unit
    - get: version-semver
      params: {bump: minor}
    - put: version-semver
      params:
        file: version-semver/number
    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: bosh/resolvconf-manager
        inputs:
        - name: version-semver
        - name: resolvconf-manager-src
        outputs:
        - name: resolvconf-manager
        - name: resolvconf-manager-shasum
        run:
          path: /bin/bash
          args:
          - -cex
          - |
            version_semver="$(cat version-semver/number)"
            set -o pipefail
            pushd resolvconf-manager-src/
              go build -o ../resolvconf-manager/resolvconf-manager-${version_semver}
            popd
    - put: resolvconf-manager-index
      params:
        files:
        - resolvconf-manager/*
        version: version-semver/number

- name: build-dockerfile
  public: true
  serial: true
  plan:
    - get: dockerfile
      trigger: true
    - put: resolvconf-manager-docker-image
      params:
        build: "dockerfile/ci/docker"
      get_params:
        skip_download: true

resources:
- name: weekly
  type: time
  source:
    interval: 168h

- name: resolvconf-manager-src
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/resolvconf-manager
    branch: master
    private_key: ((github_deployment_private_key))
    ignore_paths:
    - ci/docker

- name: dockerfile
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/resolvconf-manager
    branch: master
    private_key: ((github_deployment_private_key))
    paths:
    - ci/docker

- name: resolvconf-manager-docker-image
  type: docker-image
  source:
    repository: bosh/resolvconf-manager
    email: ((dockerhub_email))
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: resolvconf-manager-index
  type: metalink-resource
  source:
    uri: git+ssh://git@github.com:cloudfoundry-incubator/resolvconf-manager-index.git//
    mirror_files:
    - destination: s3://s3.us-west-1.amazonaws.com/bosh-resolvconf-manager/{{.Name}}
    options:
      private_key: ((index_github_deployment_key))
    url_handlers:
    - type: s3
      options:
        access_key: ((aws_bucket_access_key_id))
        secret_key: ((aws_bucket_secret_access_key))

- name: version-semver
  type: semver
  source:
    initial_version: 0.0.1
    key: resolvconf-manager-version
    bucket: bosh-resolvconf-manager
    region_name: us-west-1
    access_key_id: ((aws_bucket_access_key_id))
    secret_access_key: ((aws_bucket_secret_access_key))

resource_types:
- name: metalink-resource
  type: registry-image
  source:
    repository: dpb587/metalink-repository-resource
